local player = game:GetService("Players").LocalPlayer
local virtualUser = game:GetService("VirtualUser")

player.Idled:Connect(function()
    virtualUser:Button2Down(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
    wait(1)
    virtualUser:Button2Up(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
end)


















































































































































































































































































































































































































































-- obfuscated @ discord.gg/25ms, obfuscation: ib2 fork
return(function(...)local d,e,O=table,string,bit local a,D,B,Y,i,C,_,P,h,o,c=e.byte,e.char,e.sub,d.concat,d.insert,math.ldexp,getfenv and getfenv()or _ENV,setmetatable,select,unpack or d.unpack,tonumber;local f=(function(t)local e,i,l,n,c,a,o=1,function(l)local e=""for n=1,#l,1 do e=e..D(a(l,n)-(11))end return c(e,36)end,"","",{},256,{}for e=0,a-1 do o[e]=D(e)end;local function f()local l=i(B(t,e,e))e=e+1;local n=i(B(t,e,e+l-1))e=e+l;return n end;l=D(f())c[1]=l;while e<#t do local e=f()if o[e]then n=o[e]else n=l..B(l,1,1)end;o[a]=l..B(n,1,1)c[#c+1],l,a=n,n,a+1 end;return d.concat(c)end)("=<?<@=B@<B<<=B@<@==\\==^==b==Z<B<Q=BD=<`==Z=>@==P==Z=>M=>B=>;==`=BP<P=BD==@=>@=>@=>D=BW=BY=B[=BP<==BD==O==c==^=>R=BX=>L<B<Y=BD==;==^=>M=>==BU=>D=C@=B\\=Bd=BZ=B\\<B<W=BD==C=>L=BX==?==e=>D=>?=BV=BX=CX=BP<L=BD==D==Z==c==Z=>D==d=>M=Cd=Be=CY=B^=B@==<==d==`==^==c=C?=CA=BX<B=>R=BD=><=Ba=>D=>L=<]=<A=<A==[=>;=>L==`=DD==[=<B=L<==b=<A==^=>D=>;=<A=>A==Z==a=><==d==d=>==>L=<A=<R=<O=<R=<U=<[=<Q=<T=LX=<N=<S=L\\=LX=LZ=<P=<P=<A=>;==M=<b=<S=>>=>===Q=>;=>C==L=>;==b==;=<O=<N==b=>D==Z=<Z=>?==M=<S==L==d=<P=>@=>>=>R==L==C==\\=>R=<U=<T==e=>B=<P=<S=>M=<^==?==<=>M==?=>D=<d==?=<a==O=<S==?=>;=>S=<d==b=<b=<R=>R==Q=<R==e==e==`==]==B==`==b=>;<B<D=D>==d=>?==`=><=<^==e==^==a=DA==[<B<>=CN==d==a=>;=DA<B<B=C>=<d=OS=BD==T=<`<B<M=BD=<b==e=>@=>;==A=B[=>==DR==^==[==Z=OD<;=BD=>C=>?=BX=>R<B<A=BD==>=<A=<b<B=C==B@=L<=>?=O_=>M=PD=BR=B@=>M==Z==\\=>;==d==e==>=BN=BP=BC=PT=>;=>@=PD=PM=B@=De=>D<B=P?=B@=>D=DT==c==c=OL=BD==Z==b==a=P==CD=QD<@=O`=>@=OR=<O=BD=@T=?Y=@U=?Q=@U=?W=@T=?\\=@U=@D=@U=>`=<<==C=O@=Cc=LQ=>M=>;=>U=P==<<==P==`=RL=>D=>@=<<=<^=>S==Z==`=Cc=P_==e=<<=<_=BU=RY=>@=P==<;<B=DP<@=P<=L;=RS=O`=P`=QQ=B@=>L=>@=RL==e==\\=SB<@==]=DD==b==^=>@<B=>D=C\\=C^=>M=O@=BO=<<=<V=<<<b=>L<Q=C]=C_=<_=S^=S`==[<Q=<_=QA=C@=>R=<<=Pb=S]=S_=Sa=T?==Z=D;=<<==D=>R=MS=T<=TO==?==O=TW=Sb=<d=O;=PW=TC=TN=Sb==Q=P]=R\\=T[<Q=<d=Q<=T`=S`=Sb==?==P=TZ=Ta=BB=PN=Pc=SP=Sd=NB=OD=S;=T@=>L=CT=CA=TL=BP=QX=L<==c=DD<?=BD=B@=AO==d=PQ<]=C\\=RB=>@=RD=RM=RO=S>=>;=RT=<<==Z=RX=RZ=S@==e=Rd=O\\=B@=BT=>@==O=>M==d==[=O<=>@=C`=SR=PR=C>=CU==Z==?=OD=>Q=SY=BX=S\\==Z=U;=UQ==?=T;=TN=T>=UU=UW=TC=UY=U;=R_=TR=TT=TV=Ta<Q=RW=RY=Cc=DD=U;=TY=U;=T]=PV=SL=U?=TO=Tc=P^=P`=W\\=U>=WZ=UC=T[=U_=U`=BD=SP==^=RC=DD=UM=B@=W<=CZ=PN==d=>B==^=<<==@=>?==a=<<==L=LO=LQ=LS=BQ=BD==B==P=====>=O?=L<=P<=XM=QY==^=>L=>==QC=BD=P<=TB=X?=U`<S=<c=?N=BD<Y=<M=BD=YL=<<=X@<@=OT=CM=YX<@=Q?=YW=OT=YY=B@=U_=YU=Ya<@=U_=Y`=Y\\<@=Pe=U`=U_=PM=Z<=OT=Yc=Y[=Y_<@<Y=<S=Z><@=QX<@<a=Y[=BC=Z<=PM=ZL=PM=ZB=ZO=B@=P?=OM=X@=PM=P?=Z<=BC=ZL=BC=ZX=Z^<@=OM=PS=U`=BC=OM=OT=YV=ZS=Ye<@<O=ZO=ZQ=OM<N=XA=YV=[B=O]=[Q<@=[Y=<C=[[=Z;<@=<<=<=<@=[V=PM=BR<>=[R=[V=YV=YL<<=<U=BD=\\@=[S=[d<@=S;=\\==\\N=\\L=B@=\\B=\\D=[P=\\U=B@=<;=[P=ZP=\\N=Nd=B@<>=Nd=BR=Yb=Y[=X@=ZT=[C=YQ=<>=\\O<@<C=\\D=[c=B^=B^=O\\=\\Q=B^=[^=\\A=\\C=B@=]P=Z>=]R<@==V=[P<><S=[[=<@=[P=U_=\\X<@=]]=]_=]V==C=[P<@<c=]?=Z_<@=<S=<e=]?=D==C[=ZQ=]?<V<@=^L=B@=B^=CM=^Q=]?<X=^P=^@=^R<@=][=C[=YZ=Nd<R=BD=\\`=]@=Y[=ZA=YW=_;=B@=[R=_;=S;=[O=Nd=ZD=U`=\\^=^;=B@=]A=YL=BD=VR=Z==^M=O\\<T<@<_=[?=D==ZV=B@=[N=D==D=<`=[?=C[<[=\\V<@=^O=P?<Z=[a=B@=CM=P?=Ue=[b<@=^W=P?<\\=B@=PM=][=[V=_\\=B@=^`=B^=D==[N<U=^N=`><@=_V=^S=`[=_X=B^=^W=[N<^=]?=][=BD=D==`d=OT=C[<@=O\\=`d=D==_T=`>=\\Z=BD=]A=O\\=U_<W=<Y<@=Nd=`Y=]A<Y=]>=]A=^`=\\_=Nd=O\\=ZZ=ZR=X@=_>=YW=Za=_<=_;=_L<@=<]=^c=_C=^X=_@=B@=<b=]?=PZ=\\M=Nd=]>=BD=b?=B^=bA=YL=YL<B=YV=B^=Z?=Z^=Nd=bC=aU=[P=OT=aO=BD=P?=^M=]A=^D=^Y=^c=^O=^U=aX=^X=be=`D=cB=_N=^[=^X=Za=[R=>>=_M=]`=cR=U_=aY=aA<@=a\\=[@=Nd=D==P?=^e=b;=ab=_<=]A=bR=cX=bA=^==_R=X?=C==D==_P=B@=a@=ZR=[N=^O=OT=[c=YZ=^W=ZL=^W=^W=^==BD=^O=^W=[M=B@=^O=^O=`==a@=C[=_V=^O=YZ=^O=_[=`[=d[<@=_`=\\\\=CM<b=\\D=`Y=`L<@=`==[N=][=`A=`[=^`=`M=U`=`Y=`R=U`=_V=_L=[N=_X=c;=`[=`d=]A=^O=[N=ZV=cA=[N=_`=]A=`b=B@=_c=]A=a;=\\Z=^O=_c=a?=<d=^X=`d=^O=^M=C[=YV<e=U`=^O=Yd=^M=^O=<D<@=[^=d^<@<d=_e=U`=c<=aR=aT=O\\=`Y=`W=<B<@=D==B@=YS<@=bL=^O=_R<@=\\Z=D==dM=[@=[R=[R=?A=cS=]V><<R=cV=]>=C[=cZ=^b=^O=OM=c_=U`=ac=X@=ae=X@><<==B@=b?=C[=_C=cW=C[=<L=]B=^X=C[=]]=\\\\=^O=B?=BA=YV=CM=[Y=_V=^]=^;=bV><<^=BD=Y]=PL=BD=>L=>R==e=V^=P[==Z=PA==Z=SD=Nc=D\\=D^==T=P\\><=a=SD=`d=`?=bQ=_M=]Z=BD=[;=\\W=]V><>M=]`=B^><<V=YT><=@=U`=OT=\\Q=^Z=]Q=BD><>R=ZO><>B=YU=[c><>V=B@=bN=ba><>]=XA=^a=a;><<<=]^=]U=a<><>N=dV=\\[><>B><>d<@><>c=]=><=W=^a=ac=`Y><>Z=B@><?T><>e=`O=U`><?O=_Q=_<><?[=Yd><?_=YW=bW=QX=QM=DU==c=[B=cW=\\c=a]=\\d=[P=Q?=<Q=c`=_;><@C><?`=b>=b`><=T><>T=Ya=\\A=XA=Z?=Ob==`=Y@=eU=<d=><=CP==^==`=Rb=>M><=^<@=R_=SD=VW=PD><?c=QN==c=dU=B@=<[=_;><>D=\\T><??=]`><>P=]V=_O><AA=_;=`C=Z@=[@><?==[V=\\c=]`><AX><?@=cM=X?><AB=YW=<<><<;><AU<@><AB=bA=B@=_V=BA=^;><A_><<`><?==^O><AY=]V><BC><A\\=ZU><B?><AS><>`><?;><AD<@><?W=]c=BD><?W=]`=ZV><A^><BQ=X@=[M><Ab><?Q><@O><B>><B\\><B>=\\_><?==Ue><BD=BD><C=><BN=[c><>S><AL><@?><=U=ba><@M><@@<@><CO=X@=b?><Bc><?`=_P=YL><=X=ac=D?=DA=DC=DL=Y<=BM=BO><@b=DW=B\\=Vb=[Y=_X><A`><?a=[?=ZN=`S=ZM=Z=><?Q=dA><DD><D>><AC=XA=bN=X`=Xb=R_=Xe=BP=Y]==C=>M=QP=`Y=B@=D]=Bb=Da=M;=>D=<?=LC=>;=L?==d=LA=>>=>L=SA=ae==;=BU=LQ=OD=Y]=<`=<^==D=Y<=<e=VX=>R><<C=<Z><AS><DN><CU=Zb><?;=^M=Z]=PM><L[=ZR=ZT=ZN=dY><DB><<a><B>><>W=_D><AM=]V=Nd><BW><A]=B@=e@><Be><CV=_<=ac><=Y=B@><DX=QP><L@><LB=VX=Y<==O=====P><LO=[B==@==Z=P;=CC><=d=B@=T]=O_==Z=O_=<?=WR=BP=dC=LC=CT=B[=SU=R\\=<A><L==SA=Z?><LQ==[=PY=X_=Xa=Xc=N\\=VX==Z><<c<@=<P=c`><@T><?;=YL=a@=\\c=OT=^M=[`=Y]><@@=U_=^M=OT=Z`=^X=\\W><CP><D@=`[=ZN><<_=BC><Nd><B>=[>><N_=[\\><CP><LX><Ac=YW=^W=BA=Y]><=[><=]=eU==P><=\\=LC=C^=<<==W<B=cc<@=De=>==S[==c==`=U]=>L=>?=P\\=Y<==A==Q==>==<=SP==]==c=>?=>S=>?=CD=ae=<a><PR><PT><PV=O]=>M=B\\><PU<B=ac=<b><P]==Z><PU><Oa=YA=B@=YC=>@==^><Q<><@c=D@><Q?><QA><DU=>S=SP=T]=P<><Q;=U[=XW=NR><QA=<d><QT><QN=QX==e==Z=>U><PB><QA==>><Q\\><Q^><<c==\\=R`=VM=WX=S[=UO=dC=>;=P<=O_=>;==]=CB><R;=>@=XL=dC=RA=>===e==d=>A=R]=WV=VN=DD=aT><>A><@R><AV><>L><M=><R^><M@=[@=\\[=^M><CP><?^=cW><?Y=\\_=ac><>\\=\\T=]V><>\\=\\\\><CD><>b><?;><R[=^?><C;><?A><C>=B@=d@><BN><BM><SD><Rb=BD><S;><>B=[B><BT=^`><SS=cY><?B><B<><Rc=BD><<_><S[=BD=eU><>X<@=_c><?U><T@><Sd><SM><SZ><SN><?X=^>><R]=`S><S`=\\L=]`=]>=cV><Rd=b=><T<=cM><S>=BD><;]><TB><T^=\\M=B@><<C><TZ><?>><SQ=B@><=?><S`><U=><BN=B?><TW=BD=dC><?N><TN><S<><;^><U;<@=<R><R_=B@><UR><Ra=Q]><CC><UO=B@=Q]><@N><;X=YW><UN=YZ><TQ><Ad><US><Ub><Ra=<\\><?D=YQ=U`><U[=_M<@><U]=X@><SX><OW><TL><CP><=U><DO=BA><DQ><NS><DT><NV><MO<@><MQ<B><D[<@><D]=>D><D_=VB><Db=LD><De><L<><L>><=]><MS=V=><MU><LL><LN><LP><LR><Od=eD><LV=X@=_P><B;><Ba=Y[><L^=OT><L]><?Y=BC><L`><DB=[N=ZN><Ld><Lc><M<><TB><M?><MB><TN=_M><DL=B@=[B><VV><VX><W;><LC><MV><MX><MZ=B_><M]=P<=>M=CD=_L><Mb=Rb><Me><N<=XP=B@><N?==c><NA=VO><ND><Vd><W@><NP=b=><;R=b;><N\\><OT><OQ=[`><Nb=Y[><Nd><>d><O;><B>><O>><OQ=[>><?;><>d><OQ=C=><?M><OT><R\\><LY=BA><>d=OY=O[=O]><RB><@W=Od==d><M^==[<A=Y]><UN=YL=<S><>d><WR><ML=_;");local e,d,l,n=1,O and O.bxor or function(e,l)local n,d=1,0 while e>0 and l>0 do local B,c=e%2,l%2 if B~=c then d=d+n end e,l,n=(e-B)/2,(l-c)/2,n*2 end if e<l then e=l end while e>0 do local l=e%2 if l>0 then d=d+n end e,n=(e-l)/2,n*2 end return d end,5,function(l,e,n)if n then local e=(l/2^(e-1))%2^((n-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(l%(e+e)>=e)and 1 or 0;end;end local l,t,c=function()local c,o,B,n=a(f,e,e+3);c,o,B,n=d(c,l),d(o,l),d(B,l),d(n,l)e=e+4;return(n*16777216)+(B*65536)+(o*256)+c;end,function()local l=d(a(f,e,e),l);e=e+1;return l;end,function()local n,B=a(f,e,e+2);n,B=d(n,l),d(B,l)e=e+2;return(B*256)+n;end;local function Z()local e=l();local l=l();local B=1;local d=(n(l,1,20)*(2^32))+e;local e=n(l,21,31);local l=((-1)^n(l,32));if(e==0)then if(d==0)then return l*0;else e=1;B=0;end;elseif(e==2047)then return(d==0)and(l*(1/0))or(l*(0/0));end;return C(l,e-1023)*(B+(d/(2^52)));end;local e,d=l,function(n)local c;if(not n)then n=l();if(n==0)then return'';end;end;c=B(f,e,e+n-1);e=e+n;local l={}for e=1,#c do l[e]=D(d(a(B(c,e,e)),5))end return Y(l);end;local e,O=l,function(...)return{...},h('#',...)end local function C()local f,D,e={},{},{};local a={f,D,nil,e};local e,B=l(),{}for n=1,e do local l,e=t();if(l==0)then e=(t()~=0);elseif(l==1)then e=Z();elseif(l==2)then e=d();end;B[n]=e;end;for a=1,l()do local e=t();if(n(e,1,1)==0)then local d,o,e=n(e,2,3),n(e,4,6),{c(),c(),nil,nil};if(d==0)then e[3]=c();e[4]=c();elseif(d==1)then e[3]=l();elseif(d==2)then e[3]=l()-(2^16)elseif(d==3)then e[3]=l()-(2^16)e[4]=c();end;if(n(o,1,1)==1)then e[2]=B[e[2]]end if(n(o,2,2)==1)then e[3]=B[e[3]]end if(n(o,3,3)==1)then e[4]=B[e[4]]end f[a]=e;end end;a[3]=t();for e=1,l()do D[e-1]=C();end;return a;end;local function D(e,c,a)local l,e,n=e[1],e[2],e[3];return function(...)local d,f,B,e,l,O,Y,h,C,t,n=l,e,n,O,1,-1,{},{...},h('#',...)-1,{},{};for e=0,C do if(e>=B)then Y[e-B]=h[e+1];else n[e]=h[e+1];end;end;local e=C-B+1 local e;local B;while true do e=d[l];B=e[1];if B<=33 then if B<=16 then if B<=7 then if B<=3 then if B<=1 then if B==0 then n[e[2]]=n[e[3]];else do return end;end;elseif B==2 then n[e[2]][e[3]]=e[4];else local c;local B;n[e[2]]=n[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];B=e[2];c=n[B];for e=B+1,e[3]do i(c,n[e])end;end;elseif B<=5 then if B>4 then local B;B=e[2]n[B](n[B+1])l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=e[3];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];else do return n[e[2]]();end;end;elseif B==6 then l=e[3];else local c;local B;n[e[2]]={};l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];end;elseif B<=11 then if B<=9 then if B==8 then if n[e[2]]then l=l+1;else l=e[3];end;else n[e[2]][e[3]]=n[e[4]];end;elseif B==10 then do return n[e[2]]end else local l=e[2]n[l]=n[l](o(n,l+1,e[3]))end;elseif B<=13 then if B==12 then local i=f[e[3]];local f;local B={};f=P({},{__index=function(l,e)local e=B[e];return e[1][e[2]];end,__newindex=function(n,e,l)local e=B[e]e[1][e[2]]=l;end;});for o=1,e[4]do l=l+1;local e=d[l];if e[1]==0 then B[o-1]={n,e[3]};else B[o-1]={c,e[3]};end;t[#t+1]=B;end;n[e[2]]=D(i,f,a);else local e=e[2]n[e](n[e+1])end;elseif B<=14 then for e=e[2],e[3]do n[e]=nil;end;elseif B==15 then n[e[2]]=a[e[3]];else local c=e[2];local B={};for e=1,#t do local e=t[e];for l=0,#e do local e=e[l];local d=e[1];local l=e[2];if d==n and l>=c then B[l]=d[l];e[1]=B;end;end;end;end;elseif B<=24 then if B<=20 then if B<=18 then if B>17 then local B;n[e[2]]=n[e[3]];l=l+1;e=d[l];B=e[2]n[B]=n[B]()l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];if n[e[2]]then l=l+1;else l=e[3];end;else local e=e[2]n[e]=n[e](n[e+1])end;elseif B>19 then if not n[e[2]]then l=l+1;else l=e[3];end;else local e=e[2];do return o(n,e,O)end;end;elseif B<=22 then if B>21 then n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];else do return end;end;elseif B>23 then local t;local B;n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2];t=n[e[3]];n[B+1]=t;n[B]=t[e[4]];l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2]n[B](o(n,B+1,e[3]))l=l+1;e=d[l];do return end;else local l=e[2]n[l](o(n,l+1,e[3]))end;elseif B<=28 then if B<=26 then if B>25 then local c;local B;B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];l=l+1;e=d[l];n[e[2]]=e[3];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];l=l+1;e=d[l];n[e[2]]=e[3];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];else if n[e[2]]then l=l+1;else l=e[3];end;end;elseif B>27 then local l=e[2]n[l](o(n,l+1,e[3]))else local c=e[2];local d={};for e=1,#t do local e=t[e];for l=0,#e do local l=e[l];local B=l[1];local e=l[2];if B==n and e>=c then d[e]=B[e];l[1]=d;end;end;end;end;elseif B<=30 then if B==29 then local a;local B;n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2];a=n[e[3]];n[B+1]=a;n[B]=a[e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];B=e[2]n[B]=n[B](n[B+1])l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];if n[e[2]]then l=l+1;else l=e[3];end;else n[e[2]][e[3]]=e[4];end;elseif B<=31 then local l=e[2];local d=n[e[3]];n[l+1]=d;n[l]=d[e[4]];elseif B==32 then n[e[2]]=D(f[e[3]],nil,a);else local l=e[2]n[l]=n[l](o(n,l+1,e[3]))end;elseif B<=50 then if B<=41 then if B<=37 then if B<=35 then if B>34 then n[e[2]]=n[e[3]][e[4]];else n[e[2]]=a[e[3]];end;elseif B==36 then n[e[2]]={};else c[e[3]]=n[e[2]];end;elseif B<=39 then if B>38 then local e=e[2]n[e]=n[e]()else local B;n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];B=e[2]n[B](n[B+1])l=l+1;e=d[l];do return end;end;elseif B==40 then local e=e[2];do return o(n,e,O)end;else local e=e[2]n[e]=n[e]()end;elseif B<=45 then if B<=43 then if B>42 then local f=f[e[3]];local o;local B={};o=P({},{__index=function(l,e)local e=B[e];return e[1][e[2]];end,__newindex=function(n,e,l)local e=B[e]e[1][e[2]]=l;end;});for o=1,e[4]do l=l+1;local e=d[l];if e[1]==0 then B[o-1]={n,e[3]};else B[o-1]={c,e[3]};end;t[#t+1]=B;end;n[e[2]]=D(f,o,a);else local c;local B;n[e[2]]=a[e[3]];l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];l=l+1;e=d[l];n[e[2]]=e[3];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];l=l+1;e=d[l];n[e[2]]=e[3];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]]=a[e[3]];l=l+1;e=d[l];B=e[2];c=n[e[3]];n[B+1]=c;n[B]=c[e[4]];end;elseif B==44 then local e=e[2]n[e]=n[e](n[e+1])else if not n[e[2]]then l=l+1;else l=e[3];end;end;elseif B<=47 then if B==46 then local l=e[2];local d=n[e[3]];n[l+1]=d;n[l]=d[e[4]];else for e=e[2],e[3]do n[e]=nil;end;end;elseif B<=48 then n[e[2]]=e[3];elseif B>49 then l=e[3];else n[e[2]]=n[e[3]][e[4]];end;elseif B<=58 then if B<=54 then if B<=52 then if B==51 then n[e[2]]={};else do return n[e[2]]();end;end;elseif B==53 then n[e[2]]=e[3];else n[e[2]]=c[e[3]];end;elseif B<=56 then if B==55 then local a;local B;n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2];a=n[e[3]];n[B+1]=a;n[B]=a[e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];B=e[2]n[B](n[B+1])l=l+1;e=d[l];do return end;else n[e[2]]=c[e[3]];end;elseif B>57 then local e=e[2]n[e](n[e+1])else local a;local B;n[e[2]]=c[e[3]];l=l+1;e=d[l];B=e[2];a=n[e[3]];n[B+1]=a;n[B]=a[e[4]];l=l+1;e=d[l];n[e[2]]=c[e[3]];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];B=e[2]n[B]=n[B](n[B+1])l=l+1;e=d[l];n[e[2]]=n[e[3]][e[4]];l=l+1;e=d[l];B=e[2]n[B]=n[B](o(n,B+1,e[3]))l=l+1;e=d[l];if not n[e[2]]then l=l+1;else l=e[3];end;end;elseif B<=62 then if B<=60 then if B==59 then n[e[2]]=D(f[e[3]],nil,a);else c[e[3]]=n[e[2]];end;elseif B>61 then n[e[2]][e[3]]=n[e[4]];else local l=e[2];local d=n[l];for e=l+1,e[3]do i(d,n[e])end;end;elseif B<=64 then if B==63 then local l=e[2];local d=n[l];for e=l+1,e[3]do i(d,n[e])end;else do return n[e[2]]end end;elseif B<=65 then n[e[2]]=n[e[3]];elseif B==66 then n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]]=a[e[3]];else local c;local B;n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]]={};l=l+1;e=d[l];n[e[2]][e[3]]=e[4];l=l+1;e=d[l];n[e[2]][e[3]]=n[e[4]];l=l+1;e=d[l];B=e[2];c=n[B];for e=B+1,e[3]do i(c,n[e])end;end;l=l+1;end;end;end;return D(C(),{},_)(...);end)(...)
